
virtualenv:
  system_site_packages: true
  
before_install:
 - sudo apt-get install -qq python-numpy python-scipy

language:
 - python

python:
 - 3.4
 - 3.5
 
install:
 - pip install pytest python-coveralls numba
 
script: 
 - pytest Qfit.py

notifications:
 email: false
