language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pytest numba
  - source activate test-environment
  - pip install python-coveralls pytest-cov
  
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then py.test -vv Qfit.py MolecularIntegrals.py --cov example;
    else py.test -vv Qfit.py MolecularIntegrals.py;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]];
    then coveralls;
    fi

notifications:
  email: false
